----------------------------------------------------------------------------------
-- Company: Stanford University
-- Engineer: Jason Hogan
-- 
-- Create Date: 01/31/2020 07:25:46 PM
-- Design Name: 
-- Module Name: simplecore_top - Behavioral
-- Project Name: STI
-- Target Devices: XEM7310-A200 (xc7a200tfbg484-1)
-- Tool Versions: 
-- Description: Test methods of reducing jitter in timing module outputs.
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------


library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

Library UNISIM;
use UNISIM.vcomponents.all;

entity simplecore_top is
	port (
        okUH      : in     STD_LOGIC_VECTOR(4 downto 0);
        okHU      : out    STD_LOGIC_VECTOR(2 downto 0);
        okUHU     : inout  STD_LOGIC_VECTOR(31 downto 0);
        okAA      : inout  STD_LOGIC;
    
        sys_clkp  : in     STD_LOGIC;
        sys_clkn  : in     STD_LOGIC;
        
        led       : out    STD_LOGIC_VECTOR(7 downto 0);
    
        xbusp     :    out  STD_LOGIC_VECTOR(29 downto 0);
        xbusn     :    out  STD_LOGIC_VECTOR(29 downto 0);
        ybusp     :    out  STD_LOGIC_VECTOR(29 downto 0);
        ybusn     :    out  STD_LOGIC_VECTOR(29 downto 0)
);
end simplecore_top;

architecture simplecore_top_arch of simplecore_top is
    
    signal sys_clk  : std_ulogic;
    signal xemJ2 : STD_LOGIC_VECTOR(40 downto 1);   -- Connector J2 on XEM breakout (40 pin)
    signal stfJP0 : STD_LOGIC_VECTOR(26 downto 1);   -- Connector JP0 on any STF daughter board (34 pin, first 26 are logic)  
    signal global_rst : std_ulogic := '0';
        
    signal cbuf : unsigned(31 downto 0) := x"00000000";
    signal cbuf2 : STD_LOGIC_VECTOR(31 downto 0);
begin

    osc_clk : IBUFGDS port map (O=>sys_clk, I=>sys_clkp, IB=>sys_clkn);

stfJP0 <= ( 
            1 => cbuf2(0), 
            2 => cbuf2(0),
            25 => '1', 
            others => '0'
            );

--stfJP0 <= stf_pins_buffer(25 downto 0);


    Reg_Proc: process (sys_clk, global_rst)
    begin
      if (global_rst = '1') then
        cbuf <= X"00000000";
        
      elsif rising_edge(sys_clk) then
        cbuf <= cbuf + 1;
      end if;
    end process;

cbuf2 <= std_logic_vector(cbuf);

-- New pin names
xbusp <= (  12 => xemJ2(1),  --R3
            13 => xemJ2(2),  --Y6
            14 => xemJ2(5),  --Y3
            15 => xemJ2(6),  --AA8
            16 => xemJ2(9),  --U2
            17 => xemJ2(10), --U3
            18 => xemJ2(13), --W2
            19 => xemJ2(14), --W1
            20 => xemJ2(19), --T1
            21 => xemJ2(20), --AB3
            22 => xemJ2(23), --AA1
            23 => xemJ2(24), --Y13
            24 => xemJ2(27), --AB16
            25 => xemJ2(28), --AA13
            26 => xemJ2(31), --AA15
            27 => xemJ2(32), --W15
            28 => xemJ2(35), --Y16
            29 => xemJ2(37), --V4
            others => '1');

-- pin map from FPGA pins to XEM breakout board J2 connector 
-- note: xbus is the ouput of this component
xbusn <= (  12 => xemJ2(3),  --R2
            13 => xemJ2(4),  --AA6
            14 => xemJ2(7),  --AA3
            15 => xemJ2(8),  --AB8
            16 => xemJ2(11), --V2
            17 => xemJ2(12), --V3
            18 => xemJ2(17), --Y2
            19 => xemJ2(18), --Y1
            20 => xemJ2(21), --U1
            21 => xemJ2(22), --AB2
            22 => xemJ2(25), --AB1
            23 => xemJ2(26), --AA14
            24 => xemJ2(29), --AB17
            25 => xemJ2(30), --AB13
            26 => xemJ2(33), --AB15
            27 => xemJ2(34), --W16
            28 => xemJ2(36), --AA16
            29 => xemJ2(39), --W4
            others => '1');

-- pin map from XEM J2 connector to STF JP0 daughter board connector
-- stfJP0 is the input to this component (generated by daughter board logic)
xemJ2 <= (  10 => stfJP0(26),
            12 => stfJP0(24),
            13 => stfJP0(25),
            14 => stfJP0(22),
            17 => stfJP0(23),
            18 => stfJP0(20),
            19 => stfJP0(15),
            20 => stfJP0(18),
            21 => stfJP0(13),
            22 => stfJP0(16),
            23 => stfJP0(11),
            24 => stfJP0(14),
            25 => stfJP0(9),
            26 => stfJP0(12),
            27 => stfJP0(7),
            28 => stfJP0(10),
            29 => stfJP0(5),
            30 => stfJP0(8),
            31 => stfJP0(3),
            32 => stfJP0(6),
            33 => stfJP0(1),
            34 => stfJP0(4),
            35 => stfJP0(17),
            36 => stfJP0(2),
            37 => stfJP0(19),
            39 => stfJP0(21),          
            others => '1');


end simplecore_top_arch;
